TentSearchConfig = {
	SearchDuration = {
		min = 5,
		max = 10,
	},
	TentModels = {
		`prop_skid_tent_01b`,
		`prop_skid_tent_03`,
		`prop_skid_tent_01`,
		`prop_skid_tent_cloth`,
	},
	RepGain = 25,
	LootByRep = {
		{
			level = 0,
			loot = {
				{ name = "beer", min = 1, max = 1 },
				{ name = "water", min = 1, max = 1 },
				{ name = "chocolate_bar", min = 1, max = 1 },
				{ name = "plastic", min = 1, max = 3 },
				{ name = "scrapmetal", min = 1, max = 3 },
				{ name = "rubber", min = 1, max = 3 },
				{ name = "glue", min = 1, max = 3 },
				{ name = "cloth", min = 1, max = 1 },
				{ name = "pipe", min = 1, max = 1 },
				{ name = "nails", min = 1, max = 1 },
				{ name = "screwdriver", min = 1, max = 1 },
				{ name = "coke_bag", min = 1, max = 2 },
			},
		},
		{
			level = 3,
			loot = {
				{ name = "silverbar", min = 1, max = 1 },
				{ name = "goldbar", min = 1, max = 1 },
				{ name = "lockpick", min = 1, max = 1 },
				{ name = "beer", min = 1, max = 1 },
				{ name = "water", min = 1, max = 1 },
				{ name = "chocolate_bar", min = 1, max = 1 },
				{ name = "plastic", min = 1, max = 3 },
				{ name = "scrapmetal", min = 1, max = 3 },
				{ name = "rubber", min = 1, max = 4 },
				{ name = "glue", min = 1, max = 3 },
				{ name = "cloth", min = 1, max = 1 },
				{ name = "pipe", min = 1, max = 1 },
				{ name = "nails", min = 1, max = 1 },
				{ name = "screwdriver", min = 1, max = 1 },
				{ name = "coke_bag", min = 1, max = 2 },
			},
		},
		{
			level = 5,
			loot = {
				{ name = "goldcoins", min = 2, max = 5 },
				{ name = "ring", min = 1, max = 1 },
				{ name = "rolex", min = 1, max = 1 },
				{ name = "goldbar", min = 1, max = 1 },
				{ name = "valuegoods", min = 1, max = 1 },
				{ name = "silverbar", min = 1, max = 1 },
				{ name = "goldbar", min = 1, max = 1 },
				{ name = "lockpick", min = 1, max = 1 },
				{ name = "beer", min = 1, max = 1 },
				{ name = "water", min = 1, max = 1 },
				{ name = "chocolate_bar", min = 1, max = 1 },
				{ name = "plastic", min = 1, max = 3 },
				{ name = "scrapmetal", min = 1, max = 3 },
				{ name = "rubber", min = 1, max = 3 },
				{ name = "glue", min = 1, max = 3 },
				{ name = "cloth", min = 1, max = 1 },
				{ name = "pipe", min = 1, max = 1 },
				{ name = "nails", min = 1, max = 1 },
				{ name = "screwdriver", min = 1, max = 1 },
				{ name = "coke_bag", min = 1, max = 2 },
			},
		},
	},
}